# Exception

## 1.什么是异常

-  实际工作中,遇到的情况不可能是非常完美的.比如: 你写的某个模块,用户输入不一定符合你的要求,你的程序要打开某个文件,这个文件可能不存在或者文件格式不对,你要读取数据库的数据,数据可能是空的,我们的程序跑着,内存或者磁盘可能满了之类的
- 软件程序在运行过程中,非常可能遇到刚刚提到的这些异常问题,我们叫异常,英文是:Exception,意思是例外.这些例外情况,或者叫异常, 怎么让我们写的程序做出合法的处理.而不至于程序崩溃
- 异常指程序运行中出现的不期而至的各种状况,如:文件找不到、网络连接失败、非法参数等。
- 异常发生在程序运行期间，它影响了程序的正常运行流程。

## 2.异常分类

- 检查性异常：最具代表的检查性异常是用户错误或问题引起的异常，这是程序员无法预见的。例如要打开一个不存在的文件时，一个异常就发生了，这些异常在编译时不能被简单地忽略。
- 运行时异常：运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略。
- 错误：错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。例如当栈溢出时，一个错误就发生了，它们在编译时也检查不到。

## 3.异常体系

![image-20210221162355929](C:\Users\Administrator\AppData\Roaming\Typora\typora-user-images\image-20210221162355929.png)

## 4.Error

- Error类对象由Java虚拟机生成并抛出，大多数错误与代码编写者所执行的操作无关。
- Java虚拟机运行错误（Virtual Machine Error），当JVM不在有继续执行操作所需的内存资源时，将出现OutOfMemoryError,这些异常发生时，Java虚拟机一般会选择线程终止。
- 还有发生在虚拟机试图执行应用时，如类定义错误（NoClassDefFoundError）、链接错误（LinkageError）。这些错误是不可查的，因为它们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的状况。

## 5.Exception

- 在Exception分支中有一个重要的子类RuntimeException（运行时异常）
  - ArrayIndexOutOfBoundsException（数组下标越界）
  - NullPointException（空指针异常）
  - ArithmeticException（算术异常）
  - MissingResourceException（丢失资源）
  - ClassNotFoundException（找不到类）等异常，这些异常是不受检异常，程序中可以选择捕获处理，也可以不处理。

- 这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生；
- Error和Exception的区别：Error通常是灾难性的致命的错误，是程序无法控制和处理的，当出现这些异常时，Java虚拟机一般会选择终止线程；Exception通常情况下是可以被程序处理的，并且在程序中应该尽可能去处理这些异常。

## 6.throw 与 throws的区别

- throws：用来声明一个方法可能产生的所有异常，不做任何处理而是将异常往上传，谁调用我我就抛给谁。

​      用在方法声明后面，跟的是异常类名可以跟多个异常类名，用逗号隔开表示抛出异常，由该方法的调用者来处理
 throws表示出现异常的一种可能性，并不一定会发生这些异常

- throw：则是用来抛出一个具体的异常类型

   用在方法体内，跟的是异常对象名只能抛出一个异常对象名表示抛出异常，由方法体内的语句处理
   throw则是抛出了异常，执行throw则一定抛出了某种异常

## 7.个人总结

主要注意异常信息的解读，异常都是由内而外，最上面的方法行号是异常抛出的地方，一直抛回到方法的调用者。

![image-20210221184437705](C:\Users\Administrator\AppData\Roaming\Typora\typora-user-images\image-20210221184437705.png)

还有就是嵌套异常，就是说最里面的异常导致了外面的异常，然后一层层异常包裹了起来，最里面的异常是真正的异常。

```java
public static Throwable getRealException(Throwable t){//获取最里层的异常
    while (null != t){
        Throwable t1 = t.getCause();
        if(null == t1){
            return t;
        }
        t = t1;
    }
    return null;
}
```

自定义异常

```Java
package com.ex.ssm.config;

public class MyException extends RuntimeException  {

    private static final long serialVersionUID = -8030481791244849827L;

    public MyException() {
        super();
    }

    public MyException(String message) {
        super(message);
    }

    public MyException(Throwable t){super(t);}

    public MyException(String message,Throwable t){
        super(message,t);
    }

    public MyException(String message, boolean enableStackTrace) {
        super(message, null,false, enableStackTrace);
    }

    public MyException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
```

method.invoke()方法里面的异常没有捕获，就会出现java.lang.reflect.InvocationTargetException